# Generated by Django 5.1.4 on 2024-12-14 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
                ('data_validade', models.DateField()),
                ('serial', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Esterilização'), ('esterilizado', 'Esterilizado'), ('em_uso', 'Em Uso'), ('fora_de_uso', 'Fora de Uso')], max_length=50)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EtapaDoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_etapa', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('completa', 'Completa'), ('em_andamento', 'Em Andamento'), ('falha', 'Falha')], max_length=50)),
                ('data_inicio', models.DateTimeField()),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('tecnico_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Falha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_falha', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_falha', models.DateTimeField()),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='falhas', to='esterilizacao.etapadoprocesso')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='falhas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('tipo_esterilizacao', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('completo', 'Completo'), ('falha', 'Falha')], max_length=50)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='esterilizacao.material')),
                ('tecnico_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='etapadoprocesso',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='esterilizacao.processo'),
        ),
    ]
