# Generated by Django 5.1.4 on 2024-12-14 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esterilizacao', '0002_alter_material_serial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='tipo_esterilizacao',
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente de Esterilização'), ('recebido', 'Recebido'), ('lavado', 'Lavado'), ('esterilizado', 'Esterilizado'), ('distribuido', 'Distribuído')], max_length=50),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'Em Andamento'), ('completo', 'Completo')], max_length=50),
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completa', 'Completa'), ('em_andamento', 'Em Andamento')], max_length=50)),
                ('tipo', models.CharField(choices=[('recebimento', 'Recebimento'), ('lavagem', 'Lavagem'), ('esterilização', 'Esterilização'), ('distribuição', 'Distribuição')], max_length=50)),
                ('data_inicio', models.DateTimeField()),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='esterilizacao.processo')),
                ('tecnico_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='falha',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='falhas', to='esterilizacao.etapa'),
        ),
        migrations.DeleteModel(
            name='EtapaDoProcesso',
        ),
    ]
