# Generated by Django 5.1.4 on 2024-12-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esterilizacao', '0003_remove_processo_tipo_esterilizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente de Esterilização'), ('recebido', 'Recebido'), ('lavado', 'Lavado'), ('esterilizado', 'Esterilizado'), ('distribuido', 'Distribuído')], default='distribuido', max_length=50),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'Em Andamento'), ('completo', 'Completo')], default='em_andamento', max_length=50),
        ),
    ]
